language: c

env:
  global:
    - MAKEFLAGS=-s
  matrix:
    - TARGET=i686-nt32-midipix ARCH=nt32
    - TARGET=x86_64-nt64-midipix ARCH=nt64

before_install:
  - sudo apt-get install texinfo libgmp-dev libmpfr-dev libmpc-dev
  - git clone git://midipix.org/cbb/cbb-gcc ../cbb-gcc

before_script:
  - export WORKDIR=$(mktemp -d)
  - export PREFIX=$(mktemp -d)
  - ln -sf "$TRAVIS_BUILD_DIR" "$WORKDIR/$(echo "$TRAVIS_REPO_SLUG" | cut -f2 -d/)"
script:
  - ../cbb-gcc/cbb-midipix.sh
